# Generated by Django 3.1 on 2020-08-16 00:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import find_business.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'RESTAURANT'), (2, 'RECREATION'), (3, 'GOODS')], default=find_business.models.CompanyTypes['RESTAURANT'])),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('address', models.CharField(max_length=150, verbose_name='Company Address')),
                ('hours_start', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Company Hours Start')),
                ('hours_end', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Company Hours End')),
                ('coordinatesLon', models.FloatField(verbose_name='Coordinates Longitude')),
                ('coordinatesLat', models.FloatField(verbose_name='Coordinates Latitude')),
                ('description', models.TextField(max_length=512, verbose_name='Company Description')),
                ('rating', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Company Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Activity Title')),
                ('description', models.TextField(max_length=500, verbose_name='Activity Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_business.company')),
            ],
        ),
    ]
