# Generated by Django 3.1 on 2020-08-16 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='hours_end',
        ),
        migrations.RemoveField(
            model_name='company',
            name='hours_start',
        ),
        migrations.AddField(
            model_name='company',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 30, 17, 0), verbose_name='Company End Time'),
        ),
        migrations.AddField(
            model_name='company',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 30, 6, 0), verbose_name='Company Start Time'),
        ),
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.TextField(default='', verbose_name='Company URL'),
        ),
    ]
