# Generated by Django 3.1 on 2020-08-16 02:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_business', '0002_auto_20200815_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(default='Invalid Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default='123 N Ali Ave', max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='coordinatesLat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='company',
            name='coordinatesLon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='company',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 30, 17, 0)),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Invalid Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 30, 6, 0)),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.TextField(default='google.com'),
        ),
    ]
