# Generated by Django 3.1 on 2020-08-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_business', '0003_auto_20200815_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activities',
            field=models.TextField(default='Wears Facemasks', max_length=1024),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
